agents:
  PDM4AR_1:
    state:
      x: -5.907361417552593
      y: 9.592792681386344
      psi: -0.764035607305686
    color: saddlebrown
  PDM4AR_2:
    state:
      x: -0.5150313679876071
      y: -9.946113626046115
      psi: 1.1794289473292832
    color: steelblue
  PDM4AR_3:
    state:
      x: -5.787005471983268
      y: -7.1531591699642005
      psi: -2.695082921220803
    color: firebrick
  PDM4AR_4:
    state:
      x: 7.014463328881034
      y: -4.652302587193064
      psi: -2.8547563876254953
    color: seagreen
  PDM4AR_5:
    state:
      x: 4.253153413976628
      y: 2.3443851052764018
      psi: -0.35069552130829607
    color: indigo
  PDM4AR_6:
    state:
      x: 2.6726185694542703
      y: -5.745048196174729
      psi: -2.9574371042058942
    color: darkorange
static_obstacles:
- - - -8.220445511737385
    - -7.650114907107846
  - - -9.081189521685376
    - -6.93626163185285
  - - -8.517463559783222
    - -6.133838613585705
  - - -7.447913311662788
    - -5.833342035455668
  - - -7.222880670283828
    - -5.94982274068341
  - - -8.220445511737385
    - -7.650114907107846
- - - 5.994173824562837
    - -0.4066900146707413
  - - 6.1596989816981385
    - -2.386190329594587
  - - 5.932083969237231
    - -1.4235478976411353
  - - 5.994173824562837
    - -0.4066900146707413
- - - -4.719373768919094
    - -6.611733724334982
  - - -4.54304415747312
    - -3.3055017989952633
  - - -2.9847923275281243
    - -4.208201907165542
  - - -1.9654406890501175
    - -5.725771301067992
  - - -2.17589521400501
    - -6.340748840113074
  - - -4.719373768919094
    - -6.611733724334982
- - - 2.3671722100765686
    - -6.96845059430958
  - - 2.709467428031683
    - -7.308764740692878
  - - 3.032006596264373
    - -7.660319433721376
  - - 1.6622214194075333
    - -8.371764835219558
  - - 1.4795649960612618
    - -8.075208985220527
  - - 2.3671722100765686
    - -6.96845059430958
- - - 1.8773481840831039
    - 1.0384368475322048
  - - 4.241228895940198
    - -3.84856459659046
  - - 2.408778399066694
    - -0.09900961163598732
  - - 1.8773481840831039
    - 1.0384368475322048
- - - 4.491958094339747
    - 4.965440383135676
  - - 3.1423945149826764
    - 6.125351374097568
  - - 3.624150904522515
    - 6.707663582061688
  - - 5.300301743559531
    - 6.691979517508348
  - - 4.9082325664406765
    - 5.350660773966793
  - - 4.491958094339747
    - 4.965440383135676
- - - -5.711146484478606
    - -0.7650434445549363
  - - -5.981778948647717
    - 0.4866801898616444
  - - -4.21561656406824
    - 0.6772738506105387
  - - -5.711146484478606
    - -0.7650434445549363
- - - -2.8183763543810447
    - 5.7613643688727425
  - - -3.906764486637055
    - 5.728947777580175
  - - -7.190272934218884
    - 7.088261714118705
  - - -2.8183763543810447
    - 5.7613643688727425
- - - 8.540714454333392
    - 3.6660434651394858
  - - 8.041010757160885
    - 5.013413385103396
  - - 7.785322381243557
    - 5.899881689029568
  - - 8.502826069926565
    - 5.281310253896811
  - - 8.540714454333392
    - 3.6660434651394858
- - - 7.3726581278026275
    - -7.924424746112982
  - - 5.388008049814633
    - -8.267037805417104
  - - 5.170358530857509
    - -6.403225553962683
  - - 6.210677665925922
    - -5.853431758127622
  - - 7.3726581278026275
    - -7.924424746112982
- - - 4.410321087399876
    - 1.1984575810532974
  - - 6.363327583757888
    - 2.514814129702282
  - - 6.777952215094459
    - 2.201650798857065
  - - 4.142497855899858
    - 0.5833176470708006
  - - 4.410321087399876
    - 1.1984575810532974
- - - -6.654555604102181
    - 3.0787955369280553
  - - -6.97828541287358
    - 3.2378828413777487
  - - -7.503931249789078
    - 3.5358939399301
  - - -6.109831681604649
    - 4.055678620138307
  - - -6.245117185017568
    - 3.2343787777886366
  - - -6.654555604102181
    - 3.0787955369280553
- - - -1.2565512595509418
    - -2.5028966647897626
  - - -0.9126996947109367
    - -1.9172717505784633
  - - -0.4366607542387508
    - -1.5110096391173395
  - - -0.0046383683222013805
    - -1.7421572133956644
  - - -0.4105696893927025
    - -2.434111688915531
  - - -1.2565512595509418
    - -2.5028966647897626
- - - 1.2301979508829202
    - 3.678019094800277
  - - -1.4358629696869047
    - 1.2227718028343446
  - - 0.5754404853118498
    - 3.888170233535013
  - - 1.2301979508829202
    - 3.678019094800277
- - - -8.622844649247234
    - 0.7191694365186558
  - - -7.944395869118254
    - 0.879881465659655
  - - -8.38525751905585
    - -1.7092260667595536
  - - -9.107462376437153
    - -0.6252546140872326
  - - -8.622844649247234
    - 0.7191694365186558
- - - 0.7721437664502129
    - 8.924265986517634
  - - 2.683198902182142
    - 8.296362304063038
  - - 0.49943493814638806
    - 7.430857099762952
  - - 0.7721437664502129
    - 8.924265986517634
- - - -2.8122293698407335
    - 8.915329193797161
  - - -1.3897660552447135
    - 8.866124608581885
  - - -1.234144872596422
    - 8.37965192558628
  - - -3.624422654574622
    - 8.011483801088179
  - - -2.8122293698407335
    - 8.915329193797161
- - - 1.2708147009016786
    - -3.8736687777387355
  - - 1.2140298604588105
    - -4.376634717175736
  - - 1.070102779780664
    - -4.169772583018164
  - - 1.2708147009016786
    - -3.8736687777387355
- - - 9.028966914362558
    - -4.261564925926452
  - - 8.589378383098763
    - -4.031186646292441
  - - 8.947554658825554
    - -2.867115985319467
  - - 9.028966914362558
    - -4.261564925926452
- - - -3.6460390332893855
    - -8.41993464120566
  - - -3.616957409829011
    - -8.699741648834046
  - - -4.971690740673807
    - -8.796527831611304
  - - -5.055507611093496
    - -8.458699657454183
  - - -3.6460390332893855
    - -8.41993464120566
boundary:
- - -11.0
  - -11.0
- - -11.0
  - 11.0
- - 11.0
  - 11.0
- - 11.0
  - -11.0
- - -11.0
  - -11.0
seed: 565713
shared_goals:
- id: goal_1
  center:
  - -0.8263326333884624
  - 4.676915886637808
  radius: 0.3
- id: goal_2
  center:
  - -4.091396667580022
  - 3.8234667672876554
  radius: 0.3
- id: goal_3
  center:
  - -8.845225522222984
  - 9.63917766094631
  radius: 0.3
- id: goal_4
  center:
  - -8.45069726855741
  - 7.18057678179736
  radius: 0.3
- id: goal_5
  center:
  - 9.181169076251106
  - 8.050807421916645
  radius: 0.3
- id: goal_6
  center:
  - -3.03869130346568
  - -0.7103438525477355
  radius: 0.3
- id: goal_7
  center:
  - -5.967964508475459
  - -4.542124541612349
  radius: 0.3
- id: goal_8
  center:
  - -9.53469477262287
  - -2.288352525050324
  radius: 0.3
collection_points:
- id: collection_1
  center:
  - 9.129122691484259
  - 1.3977103737961407
  radius: 0.8
- id: collection_2
  center:
  - -0.05484330513497859
  - -5.638203990658424
  radius: 0.8
config_name: random_ex14_config
