agents:
  PDM4AR_1:
    state:
      x: 7.471567579324942
      y: -9.453735474698947
      psi: -2.3238193394742224
    color: saddlebrown
  PDM4AR_2:
    state:
      x: -7.175221292339103
      y: -5.736537120418078
      psi: -2.1560965087220634
    color: steelblue
  PDM4AR_3:
    state:
      x: -2.595977316938826
      y: -9.122683769256197
      psi: 0.11631482845256436
    color: firebrick
  PDM4AR_4:
    state:
      x: 4.4823742444632995
      y: -0.39351270759975954
      psi: -2.8158869896588037
    color: seagreen
  PDM4AR_5:
    state:
      x: 8.560820853739004
      y: 2.6618228934738184
      psi: -0.5213640322463231
    color: indigo
static_obstacles:
- - - 5.266496437300795
    - 5.356217649959932
  - - 7.183540557414156
    - 6.067527650477745
  - - 7.525782567730956
    - 5.47967247755395
  - - 7.783019109122238
    - 4.179842513611984
  - - 7.021206593393266
    - 3.9387375629907773
  - - 5.266496437300795
    - 5.356217649959932
- - - 0.896152467056651
    - -2.1640559930104075
  - - 2.5821125058596657
    - -2.6083477049253743
  - - 4.303320244980139
    - -5.11126739197774
  - - -0.17463039227827082
    - -4.151653227384453
  - - 0.896152467056651
    - -2.1640559930104075
- - - 7.170609200957761
    - -1.1139287020590942
  - - 6.817089658700449
    - -0.646537033327095
  - - 6.781004327823414
    - -0.46664050099873033
  - - 7.2051825570718
    - 0.5814887493305867
  - - 8.425479670625696
    - 0.8674456120498677
  - - 7.170609200957761
    - -1.1139287020590942
- - - -4.562411331657747
    - 0.3383459330497587
  - - -4.983403187740706
    - 0.7116506286653603
  - - -4.566448272565453
    - 0.5880811603639726
  - - -4.562411331657747
    - 0.3383459330497587
- - - 0.18778629980268224
    - 6.236159427119754
  - - 2.5562427054356354
    - 4.5741541290846595
  - - 1.1698548200936765
    - 4.726686292065135
  - - 0.18778629980268224
    - 6.236159427119754
- - - -5.300577370389584
    - -7.0172348174637555
  - - -5.130341557414562
    - -8.132112497730809
  - - -6.712732096961265
    - -8.348656701382172
  - - -6.943249746745469
    - -7.907913744331381
  - - -5.300577370389584
    - -7.0172348174637555
- - - 4.244238427427277
    - -8.594836351384838
  - - 2.903070266569942
    - -8.060248280759808
  - - 2.8695938034504693
    - -7.551246893195859
  - - 2.8958932282205345
    - -6.681817082599002
  - - 4.244238427427277
    - -8.594836351384838
- - - -0.637985802453455
    - 2.545082688016954
  - - 0.01562567575163587
    - 2.4078010323627983
  - - 1.1954575326290353
    - 1.4364175914967818
  - - 0.8323337879038929
    - 0.7329334548953406
  - - -0.4404451832441758
    - 0.12158203231305009
  - - -0.637985802453455
    - 2.545082688016954
- - - -4.997998898445633
    - 7.941941993562146
  - - -3.863595092474453
    - 5.552944192288475
  - - -5.434768955518879
    - 4.842729882374429
  - - -6.7925800946428385
    - 5.683372913665364
  - - -4.997998898445633
    - 7.941941993562146
- - - -2.988103900239987
    - -8.115943171271775
  - - -2.9421346169927167
    - -5.096244064794613
  - - -0.7383798905810552
    - -6.68124059225847
  - - -0.8527926283422067
    - -7.6956688685368135
  - - -2.2357153193458448
    - -8.009567311897875
  - - -2.988103900239987
    - -8.115943171271775
- - - 7.3503905318775296
    - -5.269682093078034
  - - 7.546990485725643
    - -7.640426818734628
  - - 7.419932809928716
    - -7.682991299916097
  - - 7.3503905318775296
    - -5.269682093078034
- - - 1.1849087523246684
    - 8.03583760839255
  - - 2.106862478051519
    - 7.619061386908584
  - - 1.9084683518464365
    - 7.333396299275038
  - - 1.1849087523246684
    - 8.03583760839255
- - - -5.704495677308218
    - -4.153282482855975
  - - -6.888397612682049
    - -2.7535901654354156
  - - -6.8713420802186285
    - -2.40105409729607
  - - -5.6059215363740025
    - -2.20012184937492
  - - -5.704495677308218
    - -4.153282482855975
- - - 3.0798778394681716
    - 1.2108871409559558
  - - 5.447184070160559
    - 1.3961556819509013
  - - 3.951896313973883
    - 0.501335573546636
  - - 3.0798778394681716
    - 1.2108871409559558
- - - 4.580443541885167
    - 7.054543978024887
  - - 4.096057778675446
    - 7.9504761407171936
  - - 4.8421212915111695
    - 8.850343814714048
  - - 4.947431477640052
    - 8.973664045110283
  - - 5.569733461441208
    - 8.434300638461572
  - - 4.580443541885167
    - 7.054543978024887
boundary:
- - -11.0
  - -11.0
- - -11.0
  - 11.0
- - 11.0
  - 11.0
- - 11.0
  - -11.0
- - -11.0
  - -11.0
seed: 1
shared_goals:
- id: goal_1
  center:
  - -8.552479287141761
  - 2.250735214935892
  radius: 0.3
- id: goal_2
  center:
  - -1.5485157804513427
  - -2.2262411736212133
  radius: 0.3
- id: goal_3
  center:
  - -0.4819614166610666
  - 3.9616588655938436
  radius: 0.3
- id: goal_4
  center:
  - 9.68380550562669
  - -2.3140647967278536
  radius: 0.3
- id: goal_5
  center:
  - 9.412137749182165
  - 5.332224422210082
  radius: 0.3
- id: goal_6
  center:
  - -9.494668685479398
  - -1.4009808553636276
  radius: 0.3
- id: goal_7
  center:
  - -3.3002647431694037
  - 1.061721675107071
  radius: 0.3
- id: goal_8
  center:
  - 8.859772250188218
  - -4.980979097855136
  radius: 0.3
- id: goal_9
  center:
  - 5.193392677506388
  - 2.59148074052227
  radius: 0.3
- id: goal_10
  center:
  - -2.7944050152332522
  - 8.865743319115854
  radius: 0.3
- id: goal_11
  center:
  - 0.5266032012635566
  - -6.372486499804534
  radius: 0.3
- id: goal_12
  center:
  - 6.09116966892366
  - -6.530837720790305
  radius: 0.3
collection_points:
- id: collection_1
  center:
  - -8.406988093184179
  - 6.8836292311425105
  radius: 0.8
config_name: random_ex14_config
